In [1]:
import numpy as np
from scipy.optimize import linprog
from itertools import combinations

In [2]:
def all_diag_combination(dim):
    possible_combination = set(combinations([-1, 1] * dim ,dim))
    return list(np.diag(item) for item in possible_combination)

In [3]:
all_diag_combination(3)

[array([[ 1,  0,  0],
        [ 0,  1,  0],
        [ 0,  0, -1]]),
 array([[-1,  0,  0],
        [ 0,  1,  0],
        [ 0,  0,  1]]),
 array([[-1,  0,  0],
        [ 0, -1,  0],
        [ 0,  0,  1]]),
 array([[ 1,  0,  0],
        [ 0, -1,  0],
        [ 0,  0, -1]]),
 array([[ 1,  0,  0],
        [ 0, -1,  0],
        [ 0,  0,  1]]),
 array([[-1,  0,  0],
        [ 0, -1,  0],
        [ 0,  0, -1]]),
 array([[-1,  0,  0],
        [ 0,  1,  0],
        [ 0,  0, -1]]),
 array([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])]

In [5]:
all_diag_combination(10)

[array([[-1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  1,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0, -1,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0, -1,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  1,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1]]),
 array([[-1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  1,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  1,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  1,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0, -1,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1]

In [13]:
dim = 10
for i in range(1, dim+1):
    print(len(all_diag_combination(i)))

2
4
8
16
32
64
128
256
512
1024


In [14]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.ones((2))

array([1., 1.])

In [16]:
np.ones((4))

array([1., 1., 1., 1.])