In [1]:
import numpy as np
from scipy.optimize import linprog
from itertools import combinations
from colorama import Fore, Back, Style

In [2]:
def all_diag_combination(dim):
    possible_combination = set(combinations([-1, 1] * dim ,dim))
    return list(np.diag(item) for item in possible_combination)

In [3]:
dim = int(input("Enter M: "))
din = int(input("Enter N: "))

Enter M: 2
Enter N: 2


In [4]:
################################# input matrix A ################################

print("Enter Matrix A :")                            
Ac = []
Au = []
delta = []
for m in range(dim):
    Ac_1 = []
    Au_1 = []
    delta_1 = []
    for n in range(din):
        value_A = input("Enter 2 numbers (with a comma in between): ")                             #input matrix A in the pattern of (a, b)
        a, b = value_A.split(',')                                                                                          #split a and b
        a, b = float(a), float(b)                                                                                          #transfrom str(a), str(b) to float(a), float(b) respectively
        Ac_1.append((a+b)*0.5)                                                                                       
        Au_1.append(b)                                                                                                    #add b(upper bound) in upper bound matrix
        delta_1.append((b-a)*0.5)
    Ac.append(Ac_1)
    Au.append(Au_1)
    delta.append(delta_1)
    
print("Center matrix of A =", Ac)
print("Upper bound matrix of A =", Au)
print("Radius matrix of A =", delta, '\n')

################################# input matrix B ################################

print("Enter Matrix B :")
Bc = []
Bl = []
tuda = []
for m in range(dim):
    value_B = input("Enter 2 numbers (with a comma in between): ")
    c, d = value_B.split(',')
    c, d = float(c), float(d)
    Bc.append((c+d)*0.5)
    Bl.append(c)
    tuda.append((d-c)*0.5)
    
print("Center matrix of B =", Bc)
print("Lower bound matrix of B =", Bl)
print('Radius matrix of B =', tuda, '\n')

################################# input matrix C ################################

print("Enter Matrix C :")
C = []
for r in range(din):
    value_C = float(input("Enter number: "))
    C.append(value_C)
    
print("Matrix C =", C)

Enter Matrix A :
Enter 2 numbers (with a comma in between): 4,6
Enter 2 numbers (with a comma in between): 9,11
Enter 2 numbers (with a comma in between): -8,-6
Enter 2 numbers (with a comma in between): 11,13
Center matrix of A = [[5.0, 10.0], [-7.0, 12.0]]
Upper bound matrix of A = [[6.0, 11.0], [-6.0, 13.0]]
Radius matrix of A = [[1.0, 1.0], [1.0, 1.0]] 

Enter Matrix B :
Enter 2 numbers (with a comma in between): -10,-8
Enter 2 numbers (with a comma in between): 13,15
Center matrix of B = [-9.0, 14.0]
Lower bound matrix of B = [-10.0, 13.0]
Radius matrix of B = [1.0, 1.0] 

Enter Matrix C :
Enter number: -1
Enter number: 3
Matrix C = [-1.0, 3.0]


In [5]:
delta_2 = delta/(np.ones((dim,din))*10)
tuda_2 = tuda/(np.ones((dim))*10)
Au_2 = Ac - delta_2
Al_2 = Ac + delta_2
Bu_2 = Bc - tuda_2
Bl_2 = Bc + tuda_2
fun_2 = []
status = []
for i in range(11):
    Au_2 += delta_2
    Al_2 -= delta_2
    Bu_2 += tuda_2
    Bl_2 -= tuda_2
    A = np.append( arr=Al_2, values=Au_2, axis=0 )
    B = np.append( arr=Bu_2, values=Bl_2, axis=0 )
    res = linprog(C, A_ub = A, b_ub = B, method = 'revised simplex' )
    status.append(res['status'])
    print('i =', i)
    if 1 in status:
        print('Iteration limit reached', '\n')
    elif 2 in status:
        print('Lower Bound:', 'Problem appears to be infeasible', '\n')
    elif 3 in status:
        print('Lower Bound:', 'Problem appears to be unbounded', '\n')
    elif 4 in status:
        print('Numerical difficulties encountered', '\n')
    elif 5 in status:
        print('No constraints; turn presolve on', '\n')
    elif 6 in status:
        print('Guess x0 cannot be converted to a basic feasible solution', '\n')
    else:
        fun_2.append(res['fun'])
        print(res['fun'], '\n')

print(fun_2, '\n')

#####################################################################################
for j in range(11):
    Status = []
    Fun = []
    for r in range(din):
        Res1 = []      
        aye = Ac - (all_diag_combination(dim)[r]).dot(delta/(np.ones((dim,din))*10)*(np.ones((dim,din))*j))
        aye = np.array(aye)
        By = Bc + (all_diag_combination(dim)[r]).dot(tuda/(np.ones((dim))*10)*(np.ones((dim))*j))
        bnd = [(0, float("inf")), (0, float("inf")), (0, float("inf")), (0, float("inf"))]
        Res = linprog(c=C, A_eq=aye, b_eq=By, bounds=bnd, method="revised simplex")
        Status.append(Res['status'])
        Fun.append(Res['fun'])
    print('i =', j)
    if 1 in Status:
        print('Iteration limit reached', '\n')
    elif 2 in Status:
        print('Lower Bound:', 'Problem appears to be infeasible', '\n')
    elif 3 in Status:
        print('Lower Bound:', 'Problem appears to be unbounded', '\n')
    elif 4 in Status:
        print('Numerical difficulties encountered', '\n')
    elif 5 in Status:
        print('No constraints; turn presolve on', '\n')
    elif 6 in Status:
        print('Guess x0 cannot be converted to a basic feasible solution', '\n')
    else:
        print(Fun)
        print('Upper bound is', '%.4f' %max(Fun), '\n')

i = 0
Lower Bound: Problem appears to be infeasible 

i = 1
Lower Bound: Problem appears to be infeasible 

i = 2
Lower Bound: Problem appears to be infeasible 

i = 3
Lower Bound: Problem appears to be infeasible 

i = 4
Lower Bound: Problem appears to be infeasible 

i = 5
Lower Bound: Problem appears to be infeasible 

i = 6
Lower Bound: Problem appears to be infeasible 

i = 7
Lower Bound: Problem appears to be infeasible 

i = 8
Lower Bound: Problem appears to be infeasible 

i = 9
Lower Bound: Problem appears to be infeasible 

i = 10
Lower Bound: Problem appears to be infeasible 

[] 



ValueError: Invalid input for linprog: unable to interpret bounds with this dimension tuple: (4, 2).

In [30]:
delta_2 = delta/(np.ones((dim,din))*10)
tuda_2 = tuda/(np.ones((dim))*10)
Au_2 = Ac - delta_2
Al_2 = Ac + delta_2
Bu_2 = Bc - tuda_2
Bl_2 = Bc + tuda_2
for i in range(11):
    Au_2 += delta_2
    Al_2 -= delta_2
    Bu_2 += tuda_2
    Bl_2 -= tuda_2
    print(Au_2)
    print(Al_2)
    print(Bu_2)
    print(Bl_2)

[[  5.   6.  -7.   8.]
 [ 10. -11.  12.  13.]]
[[  5.   6.  -7.   8.]
 [ 10. -11.  12.  13.]]
[-9. 14.]
[-9. 14.]
[[  5.1   6.1  -6.9   8.1]
 [ 10.1 -10.9  12.1  13.1]]
[[  4.9   5.9  -7.1   7.9]
 [  9.9 -11.1  11.9  12.9]]
[-8.9 14.1]
[-9.1 13.9]
[[  5.2   6.2  -6.8   8.2]
 [ 10.2 -10.8  12.2  13.2]]
[[  4.8   5.8  -7.2   7.8]
 [  9.8 -11.2  11.8  12.8]]
[-8.8 14.2]
[-9.2 13.8]
[[  5.3   6.3  -6.7   8.3]
 [ 10.3 -10.7  12.3  13.3]]
[[  4.7   5.7  -7.3   7.7]
 [  9.7 -11.3  11.7  12.7]]
[-8.7 14.3]
[-9.3 13.7]
[[  5.4   6.4  -6.6   8.4]
 [ 10.4 -10.6  12.4  13.4]]
[[  4.6   5.6  -7.4   7.6]
 [  9.6 -11.4  11.6  12.6]]
[-8.6 14.4]
[-9.4 13.6]
[[  5.5   6.5  -6.5   8.5]
 [ 10.5 -10.5  12.5  13.5]]
[[  4.5   5.5  -7.5   7.5]
 [  9.5 -11.5  11.5  12.5]]
[-8.5 14.5]
[-9.5 13.5]
[[  5.6   6.6  -6.4   8.6]
 [ 10.6 -10.4  12.6  13.6]]
[[  4.4   5.4  -7.6   7.4]
 [  9.4 -11.6  11.4  12.4]]
[-8.4 14.6]
[-9.6 13.4]
[[  5.7   6.7  -6.3   8.7]
 [ 10.7 -10.3  12.7  13.7]]
[[  4.3   5.3  -7.7   7.3]
